# Generated by Django 5.2.6 on 2025-09-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonfootprint',
            name='total_emission',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
