# Generated by Django 4.2.7 on 2025-09-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carbonfootprint_total_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonfootprint',
            name='electricity_kwh',
            field=models.FloatField(default=0, help_text='Monthly electricity consumption in kWh'),
        ),
        migrations.AddField(
            model_name='carbonfootprint',
            name='meal_type',
            field=models.CharField(choices=[('light', 'Light Meal (vegetarian/vegan)'), ('medium', 'Medium Meal (some meat)'), ('heavy', 'Heavy Meal (meat-heavy)'), ('meat_heavy', 'Meat-Heavy Diet')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='carbonfootprint',
            name='meals_per_day',
            field=models.IntegerField(default=3, help_text='Number of meals per day'),
        ),
        migrations.AddField(
            model_name='carbonfootprint',
            name='waste_kg',
            field=models.FloatField(default=0, help_text='Monthly waste generation in kg'),
        ),
        migrations.AddField(
            model_name='carbonfootprint',
            name='waste_type',
            field=models.CharField(choices=[('low', 'Low Waste (mostly recycled)'), ('medium', 'Medium Waste (some recycling)'), ('high', 'High Waste (minimal recycling)')], default='medium', max_length=20),
        ),
    ]
